# Generated by Django 3.1.7 on 2023-08-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0002_auto_20230817_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafileupload',
            name='x_test_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafileupload',
            name='y_test_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datafileupload',
            name='trained_model_data',
            field=models.BinaryField(),
        ),
    ]
